ragflow:
  host: 0.0.0.0
  http_port: 9380
mysql:
  name: 'rag_flow'
  user: 'root'
  password: 'infini_rag_flow'
  host: '44.212.5.246'
  port: 5455
  max_connections: 100
  stale_timeout: 30
minio:
  user: 'rag_flow'
  password: 'infini_rag_flow'
  host: '44.212.5.246:9000'
es:
  hosts: 'http://44.212.5.246:1200'
  username: 'elastic'
  password: 'infini_rag_flow'
infinity:
  uri: 'infinity:23817'
  db_name: 'default_db'
redis:
  db: 1
  password: 'infini_rag_flow'
  host: '44.212.5.246:6379'
